# -*- coding: utf-8 -*-
"""Ufinal poster.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tJZd9BALBi5yaqY-qnxf--W_NPvNkbkH
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    roc_auc_score, accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix, RocCurveDisplay, classification_report
)

# Make plots readable
plt.rcParams["figure.figsize"] = (8, 5)

path = "Heart Disease data .csv"   # change if needed
df = pd.read_csv(path)

print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
df.head()

id_candidates = ["PatientID", "Patient ID", "ID"]
for c in id_candidates:
    if c in df.columns:
        df = df.drop(columns=[c])

target = "HadHeartAttack"

# Many versions store Yes/No; map safely to 0/1 if needed
if df[target].dtype == "object":
    df[target] = df[target].str.strip().str.lower().map({"yes": 1, "no": 0})

df[target] = df[target].astype(int)
df[target].value_counts()

leak_cols = ["HadAngina", "HadStroke", "HighRiskLastYear"]
leak_cols_present = [c for c in leak_cols if c in df.columns]
print("Dropping leakage columns:", leak_cols_present)

df = df.drop(columns=leak_cols_present)

if "AgeCategory" in df.columns and df["AgeCategory"].dtype == "object":
    s = df["AgeCategory"].astype(str)

    # Extract first number
    lo = s.str.extract(r"(\d+)")[0].astype(float)

    # Extract second number if present (e.g., 65 to 69)
    hi = s.str.extract(r"to\s*(\d+)")[0].astype(float)

    # If no upper bound, approximate:
    # - "80 or older" -> lo + 5
    # - otherwise fallback to lo
    age_mid = np.where(hi.notna(), (lo + hi)/2, lo + 5)

    df["Age"] = age_mid
    df = df.drop(columns=["AgeCategory"])

"""EDA"""

counts = df[target].value_counts().sort_index()
rates = df[target].value_counts(normalize=True).sort_index()

print("Counts:\n", counts)
print("\nRates:\n", rates.round(3))

plt.figure()
plt.bar(["No", "Yes"], [counts.get(0,0), counts.get(1,0)])
plt.title("Target Distribution: HadHeartAttack")
plt.ylabel("Count")
plt.show()

if "State" in df.columns:
    state_n = df["State"].value_counts()
    state_rate = df.groupby("State")[target].mean()

    # Only show states with enough samples (avoid noisy tiny groups)
    min_n = 500
    keep_states = state_n[state_n >= min_n].index
    state_rate_plot = state_rate.loc[keep_states].sort_values()

    plt.figure(figsize=(9, 10))
    plt.barh(state_rate_plot.index, state_rate_plot.values)
    plt.title(f"Heart Attack Rate by State (n≥{min_n})")
    plt.xlabel("Proportion reporting heart attack")
    plt.tight_layout()
    plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Select the top 10 states with highest heart attack prevalence and sort them in descending order
top_10_states_risk = state_rate_plot.tail(10).sort_values(ascending=False)

plt.figure(figsize=(12, 8))
sns.barplot(x=top_10_states_risk.values, y=top_10_states_risk.index, hue=top_10_states_risk.index, palette='viridis', legend=False)
plt.title('Top 10 States with Highest Heart Attack Prevalence', fontsize=16)
plt.xlabel('Proportion Reporting Heart Attack', fontsize=12)
plt.ylabel('State', fontsize=12)
plt.tight_layout()
plt.show()

def boxplot_by_target(col):
    if col in df.columns and pd.api.types.is_numeric_dtype(df[col]):
        data0 = df.loc[df[target]==0, col].dropna()
        data1 = df.loc[df[target]==1, col].dropna()

        plt.figure()
        plt.boxplot([data0, data1], labels=["No Heart Attack", "Heart Attack"])
        plt.title(f"{col} by Heart Attack History")
        plt.ylabel(col)
        plt.show()

for col in ["Age", "BMI"]:
    boxplot_by_target(col)

def rate_bar_by_category(col, top_n=12, display_name=None):
    if col in df.columns:
        # If too many categories (like long states), limit to top_n by frequency
        vc = df[col].value_counts()
        cats = vc.index[:top_n]
        sub = df[df[col].isin(cats)]
        rates = sub.groupby(col, observed=False)[target].mean().sort_values()

        plt.figure(figsize=(8, 5))
        sns.barplot(x=rates.index.astype(str), y=rates.values, palette='viridis', hue=rates.index.astype(str), legend=False)
        title_text = display_name if display_name else col
        plt.title(f"Heart Attack Rate by {title_text}")
        plt.xlabel("Proportion reporting heart attack")
        plt.tight_layout()
        plt.show()

for col in ["SmokerStatus", "HadDiabetes", "GeneralHealth", "Sex", "RaceEthnicityCategory", "DifficultyWalking"]:
    rate_bar_by_category(col)

"""### Simplifying 'SmokerStatus' and 'HadDiabetes' to binary 'Yes'/'No' for plotting"""

# Create a copy of the DataFrame to add new binary columns for plotting
df_plot = df.copy()

# Map 'HadDiabetes' to binary 'Yes'/'No'
diabetes_map = {
    'Yes': 'Yes',
    'No': 'No',
    'Yes, but only during pregnancy (female)': 'Yes',
    'No, pre-diabetes or borderline diabetes': 'No'
}
df_plot['HadDiabetes_Binary'] = df_plot['HadDiabetes'].map(diabetes_map)

# Map 'SmokerStatus' to binary 'Yes'/'No' (Smoker/Non-smoker)
smoker_map = {
    'Current smoker - now smokes every day': 'Yes',
    'Current smoker - now smokes some days': 'Yes',
    'Former smoker': 'No',
    'Never smoked': 'No'
}
df_plot['SmokerStatus_Binary'] = df_plot['SmokerStatus'].map(smoker_map)

# Plot the binary versions of HadDiabetes and SmokerStatus
# Temporarily change the df to df_plot for the function call
original_df = df # Store original df
df = df_plot # Assign df_plot to df for the function call

print("Plotting 'Heart Attack Rate by HadDiabetes (Yes/No)'")
rate_bar_by_category('HadDiabetes_Binary', top_n=2, display_name='HadDiabetes ')

print("Plotting 'Heart Attack Rate by SmokerStatus (Yes/No)'")
rate_bar_by_category('SmokerStatus_Binary', top_n=2, display_name='SmokerStatus ')

# Restore original df
df = original_df

"""### Heart Attack Rate by Age Group"""

# Create age bins from the 'Age' column
# Define the bins and labels for age groups
age_bins = [20, 30, 40, 50, 60, 70, 80, 100]
age_labels = ['20-29', '30-39', '40-49', '50-59', '60-69', '70-79', '80+']

df['AgeGroup'] = pd.cut(df['Age'], bins=age_bins, labels=age_labels, right=False)

# Plot the heart attack rate by the newly created AgeGroup
print("Plotting 'Heart Attack Rate by Age Group'")
rate_bar_by_category('AgeGroup', top_n=len(age_labels), display_name='Age Group')

# Drop the temporary AgeGroup column after plotting if not needed for further analysis
df = df.drop(columns=['AgeGroup'])

"""Modelling"""

df_model = df.copy()

# Optional: drop State to keep the model focused on clinical/behavioral factors
# (If you want state as a feature, comment this out.)
if "State" in df_model.columns:
    df_model = df_model.drop(columns=["State"])

X = df_model.drop(columns=[target])
y = df_model[target]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Train:", X_train.shape, "Test:", X_test.shape)

cat_cols = X_train.select_dtypes(include=["object", "category", "bool"]).columns.tolist()
num_cols = [c for c in X_train.columns if c not in cat_cols]

preprocess = ColumnTransformer(
    transformers=[
        ("cat", Pipeline([
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("onehot", OneHotEncoder(handle_unknown="ignore"))
        ]), cat_cols),
        ("num", Pipeline([
            ("imputer", SimpleImputer(strategy="median"))
        ]), num_cols),
    ]
)

print("Categorical cols:", cat_cols)
print("Numeric cols:", num_cols[:10], "...")

log_model = Pipeline([
    ("prep", preprocess),
    ("log", LogisticRegression(max_iter=2000, class_weight="balanced"))
])

rf_model = Pipeline([
    ("prep", preprocess),
    ("rf", RandomForestClassifier(
        n_estimators=350,
        random_state=42,
        n_jobs=-1,
        class_weight="balanced_subsample",
        min_samples_leaf=2
    ))
])

log_model.fit(X_train, y_train)
rf_model.fit(X_train, y_train)

def eval_model(name, model):
    proba = model.predict_proba(X_test)[:, 1]
    pred = (proba >= 0.5).astype(int)

    out = {
        "Model": name,
        "Accuracy": accuracy_score(y_test, pred),
        "Precision": precision_score(y_test, pred, zero_division=0),
        "Recall": recall_score(y_test, pred, zero_division=0),
        "F1": f1_score(y_test, pred, zero_division=0),
        "ROC-AUC": roc_auc_score(y_test, proba)
    }
    return out, proba, pred

log_res, log_proba, log_pred = eval_model("Logistic Regression", log_model)
rf_res, rf_proba, rf_pred = eval_model("Random Forest", rf_model)

results = pd.DataFrame([log_res, rf_res]).round(3)
results

"""Poster visual"""

plt.figure(figsize=(7, 5))
RocCurveDisplay.from_predictions(y_test, log_proba, name="Logistic")
RocCurveDisplay.from_predictions(y_test, rf_proba, name="Random Forest")
plt.title("ROC Curve: Heart Attack Models")
plt.show()

def plot_cm(cm, title):
    plt.figure(figsize=(4.6, 4))
    plt.imshow(cm, cmap="Blues")

    plt.title(title)
    plt.xticks([0,1], ["Pred 0","Pred 1"])
    plt.yticks([0,1], ["Actual 0","Actual 1"])
    for (i,j), v in np.ndenumerate(cm):
        plt.text(j, i, str(v), ha="center", va="center")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.tight_layout()
    plt.show()

plot_cm(confusion_matrix(y_test, rf_pred), "Confusion Matrix: Random Forest")

# Get feature names after encoding
feature_names = rf_model.named_steps["prep"].get_feature_names_out()

# Clean names ONCE
feature_names_clean = [
    f.replace("cat__", "")
     .replace("num__", "")
     .replace("_Yes", "")
     .replace("_No", "")
    for f in feature_names
]

importances = rf_model.named_steps["rf"].feature_importances_

top_k = 12
idx = np.argsort(importances)[::-1][:top_k]

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Create gradient palette
palette = sns.color_palette("crest", top_k)

plt.figure(figsize=(9,5))
plt.barh(np.array(feature_names_clean)[idx][::-1],
         importances[idx][::-1],
         color=palette)

plt.title("Feature Importance (Random Forest)")
plt.xlabel("Importance")
plt.tight_layout()
plt.show()
plt.figure(figsize=(9, 5))
plt.barh(np.array(feature_names_clean)[idx][::-1], importances[idx][::-1])
plt.title("Feature Importance (Random Forest)")
plt.xlabel("Importance")
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

sex_rates = df.groupby("Sex")[target].mean().sort_values()

plt.figure(figsize=(4, 5))
sns.barplot(x=sex_rates.index, y=sex_rates.values, palette='viridis', hue=sex_rates.index, legend=False)
plt.title("Heart Attack Rate by Gender")
plt.ylabel("Proportion reporting heart attack")
plt.xlabel("Gender")
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Plotting Top 10 Highest Odds Ratios
plt.figure(figsize=(10, 8))
sns.barplot(x='OddsRatio', y='Feature', data=or_df_cleaned.head(10), palette='viridis', hue='Feature', legend=False)
plt.title('Odds Ratios from Logistic Regression')
plt.xlabel('Odds Ratio')
plt.ylabel('Feature')
plt.axvline(x=1, color='black', linestyle='--')
plt.tight_layout()
plt.show()

# Plotting Top 10 Lowest Odds Ratios
plt.figure(figsize=(10, 8))
sns.barplot(x='OddsRatio', y='Feature', data=or_df_cleaned.tail(10).sort_values('OddsRatio', ascending=True), palette='magma', hue='Feature', legend=False)
plt.title('Odds Ratios from Logistic Regression')
plt.xlabel('Odds Ratio')
plt.ylabel('Feature')
plt.axvline(x=1, color='black', linestyle='--')
plt.tight_layout()
plt.show()

def clean_feature_names(df, col_name):
    df[col_name] = df[col_name].apply(lambda x:
        x.replace("cat__", "")
         .replace("num__", "")
         .replace("_Yes", "")
         .replace("_No", "")
         .replace("_Male", "")
         .replace("_Female", "")
         .replace("_Current smoker - now smokes every day", "_Smoker")
         .replace("_Current smoker - now smokes some days", "_Smoker")
         .replace("_Former smoker", "_NonSmoker")
         .replace("_Never smoked", "_NonSmoker")
         .replace("_No, pre-diabetes or borderline diabetes", "_PreDiabetes")
         .replace("_Yes, but only during pregnancy (female)", "_PregnancyDiabetes")
    )
    return df

or_df_cleaned = clean_feature_names(or_df.copy(), 'Feature')

print("Top 15 features with highest odds ratios (cleaned names):")
display(or_df_cleaned.head(15))

print("\nTop 15 features with lowest odds ratios (cleaned names):")
display(or_df_cleaned.tail(15))

display(or_df.head(15))

"""And here are the 15 features with the lowest odds ratios, indicating a stronger negative association with heart attack:

"""

display(or_df.tail(15))

import seaborn as sns

# Get feature names after encoding
feature_names = rf_model.named_steps["prep"].get_feature_names_out()

# Clean names ONCE
feature_names_clean = [
    f.replace("cat__", "")
     .replace("num__", "")
     .replace("_Yes", "")
     .replace("_No", "")
    for f in feature_names
]

importances = rf_model.named_steps["rf"].feature_importances_

top_k = 12

# Find the index of 'Age'
age_feature_index = np.where(np.array(feature_names_clean) == 'Age')[0][0]

# Create a temporary importances array to sort other features, giving 'Age' a very low value
temp_importances = importances.copy()
temp_importances[age_feature_index] = -1.0 # Ensures 'Age' is not picked by the general sort

# Get indices of all features sorted by importance (descending) excluding 'Age'
remaining_sorted_indices = np.argsort(temp_importances)[::-1]

# Construct the new index list: 'Age' first, then the next top_k-1 features
new_idx_for_plot = [age_feature_index]
count = 0
for i in remaining_sorted_indices:
    if i != age_feature_index:
        new_idx_for_plot.append(i)
        count += 1
    if count == top_k - 1:
        break

# Reverse the order for plotting so 'Age' appears at the top
idx_plot_order = np.array(new_idx_for_plot)[::-1]

plt.figure(figsize=(9, 5))
sns.barplot(x=importances[idx_plot_order], y=np.array(feature_names_clean)[idx_plot_order], palette='viridis', hue=np.array(feature_names_clean)[idx_plot_order], legend=False)
plt.title("Feature Importance (Random Forest)")
plt.xlabel("Importance")
plt.ylabel("Feature")
plt.tight_layout()
plt.show()

"""Poster table"""

feature_names_log = log_model.named_steps["prep"].get_feature_names_out()
coefs = log_model.named_steps["log"].coef_.ravel()
odds = np.exp(coefs)

or_df = pd.DataFrame({
    "Feature": feature_names_log,
    "OddsRatio": odds
}).sort_values("OddsRatio", ascending=False)

or_df.head(15)

heart_attack_prevalence = rates.get(1, 0)
print(f"Heart attack prevalence: {heart_attack_prevalence:.3f} ({heart_attack_prevalence*100:.1f}%)")

or_df.tail(15)

from sklearn.metrics import PrecisionRecallDisplay

PrecisionRecallDisplay.from_predictions(y_test, log_proba)
plt.title("Precision-Recall Curve (Logistic Regression)")
plt.show()

from sklearn.metrics import recall_score, precision_score, f1_score

proba = log_model.predict_proba(X_test)[:,1]

thresholds = [0.5, 0.4, 0.35, 0.3, 0.25]

print("Threshold Tuning (Logistic Regression)")
print("---------------------------------------")

for t in thresholds:
    pred = (proba >= t).astype(int)
    recall = recall_score(y_test, pred)
    precision = precision_score(y_test, pred)
    f1 = f1_score(y_test, pred)

    print(f"Threshold: {t}")
    print(f"Recall: {recall:.3f}")
    print(f"Precision: {precision:.3f}")
    print(f"F1: {f1:.3f}")
    print()

from sklearn.metrics import PrecisionRecallDisplay, average_precision_score

# Use Logistic probabilities
proba = log_model.predict_proba(X_test)[:, 1]

# Plot Precision-Recall curve
plt.figure(figsize=(7,5))
PrecisionRecallDisplay.from_predictions(y_test, proba)
plt.title("Precision-Recall Curve (Logistic Regression)")
plt.show()

# Compute Average Precision (area under PR curve)
ap = average_precision_score(y_test, proba)
print(f"Average Precision (AP): {ap:.3f}")

"""```mermaid
graph TD
    A[Start] --> B(Load Data);
    B --> C{Data Cleaning & Preprocessing};
    C --> C1(Drop PatientID);
    C1 --> C2(Map Target Variable);
    C2 --> C3(Drop Leakage Columns);
    C3 --> C4(Process AgeCategory);
    C4 --> D{Exploratory Data Analysis (EDA)};
    D --> D1(Target Distribution);
    D1 --> D2(State-wise Rates);
    D2 --> D3(Numeric Feature Boxplots);
    D3 --> D4(Categorical Feature Barplots);
    D4 --> E{Model Preparation};
    E --> E1(Train-Test Split);
    E1 --> E2(Define Preprocessing Pipeline);
    E2 --> F{Model Training};
    F --> F1(Logistic Regression);
    F --> F2(Random Forest);
    F1 --> G{Model Evaluation};
    F2 --> G;
    G --> G1(Calculate Metrics);
    G1 --> G2(Plot ROC Curves);
    G2 --> G3(Plot Confusion Matrix);
    G3 --> G4(Plot Feature Importance);
    G4 --> G5(Plot Precision-Recall Curve);
    G5 --> H{Interpretation & Conclusion};
    H --> I[End];
```
"""